#!/bin/bash

in="/dev/stdin"
out="/dev/stdout"

sed '{
s/^[ ]*//
s/[ ]*$//
s/  */ /g
1 s/.*/<html>\
<head>\
    <meta http-equiv="Content-Type" content="text\/html; charset=UTF-8" \/>\
    <title>&<\/title>\
<\/head>\
<body>/
2,$ {
/.*%.*/ {
d
}
/^\\section{[^}]*}$/ {
s/^\\section{\([^}]*\)}$/<h1>\1<\/h1>/
x
s/..*/<p>&<\/p>/
s/^<p>\n/<p>/
}
/^\\subsection{[^}]*}$/ {
s/^\\subsection{\([^}]*\)}$/<h2>\1<\/h2>/
x
s/..*/<p>&<\/p>/
s/^<p>\n/<p>/
}
/[^>]$/ {
$ !{
H
d
}
$ {
H
x
s/^$//
s/.*/<p>&<\/p>/
}
}
/^$/ {
x
/.*/ {
s/^[<].*/&/
s/^[^<].*/<p>&<\/p>/
}
 }
/^$/ {
d
}
s/^<p>\n/<p>/
s/<\/p>\n/<\/p>/
s/^<h1>\n/<h1>/
/^<p><\/p>$/ {
$ !{
d
}
}
}
$ s/.*/&\
<\/body>\
<\/html>/
$ s/<p><\/p>\n//
}' <"$in" >"$out"